version: "3.8"

services: 
  app:
    image: node:14
    command: npm run dev
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - 3000:3000
      - 9229:9229
    depends_on: 
      - database
    environment: 
      JWT_SECRET: mysecret
      DB_HOST: database
      DB_USER: hermes
      DB_PASS: hermes
      DB_NAME: hermes

  database:
    image: postgres
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes
      POSTGRES_DB: hermes
